import './style.css';
import './hud.css';
import './experience.css';
import './english.css';
import { motion, center } from './motion';
import { cardInput } from './card-input';

import { Engine, type Run, type Enemy } from './engine';
import { CARDS, RELICS, ENEMIES, NODE_INFO, KEYWORDS, KIND_LABEL, RARITY_LABEL, cost, cardText, cardName, type Card } from './data';
import { world, positions } from './world';
const app=document.querySelector<HTMLDivElement>('#app')!;
const scenario=import.meta.env.DEV&&new URLSearchParams(location.search).has('ohmygamePlaytest')?new URLSearchParams(location.search).get('scenario'):null;
const SAVE=scenario?`ember-route-qa-${scenario}`:'ember-route-save-v1',SETTINGS='ember-route-settings-v1';
let engine:Engine|undefined,selected:number|undefined,rewardSelected:string|undefined,target:number|undefined;
let modal:string|undefined,busy=false,muted=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let actionEpoch=0;
let displayed:{hp:number;gold:number;deck:number;energy:number;heat:number;block:number;phase:number}|undefined;
try{const settings=JSON.parse(localStorage.getItem(SETTINGS)??'{}');muted=settings.muted??false;reduced=settings.reduced??reduced;}catch{}
const art=(name:string)=>`${import.meta.env.BASE_URL}art/${name}.webp`;
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(label:string,action:string,classes='',disabled=false,extra='')=>`<button class="button ${classes}" data-action="${action}" ${disabled?'disabled':''} ${extra}>${label}</button>`;
function loadSave():Run|undefined{try{const r=JSON.parse(localStorage.getItem(SAVE)??'null');if(r?.version===1&&Array.isArray(r.deck)&&Array.isArray(r.map))return r;}catch{}return undefined;}
function save(){if(engine)try{localStorage.setItem(SAVE,JSON.stringify(engine.run));}catch{notify('Progress could not be saved in this browser.');}}
function notify(s:string){const host=document.querySelector('#notifications')!;host.replaceChildren();const n=document.createElement('div');n.className='toast';n.setAttribute('role','status');const mark=document.createElement('span');mark.className='toast-mark';mark.textContent='◇';mark.setAttribute('aria-hidden','true');const text=document.createElement('span');text.className='toast-copy';text.textContent=s;n.append(mark,text);host.append(n);setTimeout(()=>{n.classList.add('toast-leaving');setTimeout(()=>n.remove(),180);},import.meta.env.DEV&&scenario==='cards'?15000:3200);}
function tone(kind='card'){motion.sound(kind);}
const icon=(name:string)=>`<img class="ui-icon" src="${art(`ui-${name}`)}" alt="" aria-hidden="true"/>`;
const nodeIcon=(kind:string)=>icon(({battle:'hammer',elite:'skull',rest:'rest',shop:'coin',event:'event',chest:'chest',boss:'bell',start:'energy'} as Record<string,string>)[kind]??'event');
function card(c:Card,action?:string,extra='',large=false){const d=CARDS[c.id];return `<button class="card ${d.kind==='攻击'?'attack':d.kind==='能力'?'power':'skill'} ${d.rarity==='稀有'?'rare':''} ${c.upgraded?'upgraded':''} ${extra} ${large?'large':''}" ${action?`data-action="${action}"`:''} data-uid="${c.uid}" aria-label="${esc(cardName(c))}, ${cost(c)===99?'Unplayable':`${cost(c)} Energy`}, ${esc(cardText(c))}" ${action?'':'type="button"'}>
 <span class="cost">${cost(c)===99?'—':cost(c)}</span><div class="card-art" style="background-image:url('${art(`card-${d.art}`)}')"></div><div class="card-name">${cardName(c)}</div><div class="card-type" title="${KIND_LABEL[d.kind]} · ${RARITY_LABEL[d.rarity]}">${icon(d.kind==='攻击'?'sword':d.kind==='能力'?'energy':'shield')}<span>${d.rarity==='稀有'?'◆◆◆':d.rarity==='精良'?'◆◆':'◆'}</span></div><div class="card-text"><span>${esc(cardText(c)).replace(/\d+/g,n=>`<b>${n}</b>`)}</span>${c.bonus?`<strong>Sigil bonus +${c.bonus}</strong>`:''}</div>${d.retain||c.keep?'<span class="retain-mark">Retain</span>':''}</button>`;}
function relic(i:number,large=false){return `<div class="relic ${large?'large-relic':''}" title="${esc(RELICS[i].name+': '+RELICS[i].text)}"><img src="${art(`relic-${i}`)}" alt="${RELICS[i].name}"/>${large?`<h3>${RELICS[i].name}</h3><p>${RELICS[i].text}</p>`:''}</div>`;}
function header(r:Run){return `<header class="hud"><div class="hud-left"><button class="brand" data-action="home" aria-label="Open run menu">${icon('energy')}</button><div class="hp-stat" title="Health">${icon('heart')}<b>${r.hp}</b><span> / ${r.maxHp}</span></div><div class="gold-stat" title="Gold">${icon('coin')}<b>${r.gold}</b></div></div><div class="hud-right"><button class="relic-bar" data-action="relics" aria-label="View relics">${r.relics.map(i=>relic(i)).join('')}</button><button class="icon-button" data-action="deck" title="View deck" aria-label="View deck">${icon('deck')}<span>${r.deck.length}</span></button><button class="icon-button" data-action="settings" aria-label="Settings">${icon('gear')}</button></div></header>`;}
function menu(){const saved=loadSave(),canContinue=saved&&saved.screen!=='finish';return `<main class="main-menu"><div class="menu-copy"><h1 class="menu-title"><span>Ember</span><span>Route</span></h1><div class="menu-actions">${canContinue?button('Continue','continue','primary'):''}${button('New Journey',canContinue?'new-confirm':'new',canContinue?'quiet':'primary')}</div></div><img class="menu-hero" src="${art('hero')}" alt="Lan, the lantern smith"/><button class="menu-settings icon-button" data-action="settings" aria-label="Settings">${icon('gear')}</button></main>`;}
function pageTitle(over:string,title:string,text:string){return `<div class="page-heading"><div class="eyebrow">${over}</div><h1>${title}</h1><p>${text}</p></div>`;}
function forge(){return `<main class="choice-screen forge-screen">${pageTitle('THE LAST LANTERN','Choose your first sigil','Upgrade one starting card.')}<div class="choice-cards">${['C01','C02','C03'].map(id=>{const c={uid:0,id,upgraded:true};return `<div>${card(c,`forge:${id}`,'',true)}<p class="choice-caption">${id==='C01'?'Sharper strikes':id==='C02'?'Stronger defense':'More cards'}</p></div>`;}).join('')}</div><p class="subtle">68 HP · 80 gold · 10 cards · Old Furnace Core</p></main>`;}
function map(r:Run){
 const available=engine!.available(),map=r.map;const gap=window.innerWidth<650?88:96;const height=gap*12+112;const width=520;
 const pos=(n:typeof map[number])=>({x:120+n.col*140,y:height-56-n.floor*gap});
 const lines=map.flatMap(n=>n.next.map(id=>{const next=map.find(v=>v.id===id)!,a=pos(n),b=pos(next),traveled=r.path.includes(n.id)&&r.path.includes(id);return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="${traveled?'walked-line':'future-line'}"/>`;})).join('');
 return `<main class="map-screen" aria-label="Route map"><div class="map-scroll" tabindex="0" role="region" aria-label="Route nodes"><div class="route-chart" style="height:${height}px"><svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" aria-hidden="true">${lines}</svg>${map.map(n=>{const p=pos(n),info=NODE_INFO[n.kind],done=r.path.includes(n.id),active=available.includes(n.id);return `<button class="route-node ${n.kind} ${done?'visited':''} ${active?'available':''} ${n.id===r.current?'current':''}" style="left:${p.x/width*100}%;top:${p.y}px" data-action="node:${n.id}" aria-label="Floor ${n.floor}, ${info.name}${active?', available':''}" aria-disabled="${!active}" title="Floor ${n.floor} · ${info.name}: ${info.hint}"><span>${done&&n.id!==r.current?'✓':nodeIcon(n.kind)}</span><small>${n.kind==='boss'?ENEMIES.boss.name:active?info.name:''}</small></button>`;}).join('')}</div></div><aside class="map-legend" aria-label="Node legend">${(['battle','elite','rest','shop','event','chest'] as const).map(kind=>`<div><span>${nodeIcon(kind)}</span><p>${NODE_INFO[kind].name}</p></div>`).join('')}</aside></main>`;
}
function statuses(s:{block:number;burn:number;weak:number;vulnerable:number;strength:number}){return [s.block?`<span class="block" title="Block ${s.block}">${icon('shield')}${s.block}</span>`:'',s.burn?`<span class="burn" title="Burn ${s.burn}">${icon('energy')}${s.burn}</span>`:'',s.weak?`<span title="Weak ${s.weak}">${icon('sword')}↓${s.weak}</span>`:'',s.vulnerable?`<span title="Vulnerable ${s.vulnerable}">${icon('shield')}↓${s.vulnerable}</span>`:'',s.strength?`<span title="Strength +${s.strength}">${icon('sword')}+${s.strength}</span>`:''].join('');}
function intentMarkup(e:Enemy){const a=engine!.action(e),parts:string[]=[];const badge=(name:string,value:string,title:string)=>`<span title="${title}">${icon(name)}<b>${value}</b></span>`;
 if(a.damage)parts.push(badge('sword',`${engine!.attackDamage(a.damage,e,engine!.b.player)}${(a.hits??1)>1?`×${a.hits}`:''}`,'Attack'));
 if(a.block||a.allBlock)parts.push(badge('shield',`${a.block??a.allBlock}`,a.allBlock?'Block for all enemies':'Block'));
 if(a.weak)parts.push(badge('sword',`↓${a.weak}`,'Apply Weak'));if(a.burn)parts.push(badge('energy',`${a.burn}`,'Apply Burn'));if(a.junk)parts.push(badge('deck',`+${a.junk}`,'Add Cinder'));if(a.heat)parts.push(badge('heat',`+${a.heat}`,'Gain Heat'));if(a.strength)parts.push(badge('sword',`+${a.strength}`,'Gain Strength'));return parts.join('');
}
function enemyPanel(e:Enemy,x:number,y:number,height:number,r:Run){if(e.hp<=0)return '';const selectedCard=r.battle!.hand.find(c=>c.uid===selected);return `<button class="enemy-target ${selectedCard&&CARDS[selectedCard.id].target?'targeting':''} ${target===e.uid?'chosen-target':''}" data-action="target:${e.uid}" data-testid="enemy-${e.uid}" style="left:${x}px;top:${y-height-43}px;height:${height+72}px" title="${ENEMIES[e.id].name} · ${engine!.intention(e)}" aria-label="${ENEMIES[e.id].name}, ${e.hp} HP, next: ${engine!.intention(e)}"><div class="intent">${intentMarkup(e)}</div><div class="target-space"></div><div class="actor-bar"><div class="health-track"><i style="width:${e.hp/e.maxHp*100}%"></i><span>${e.hp}</span></div><div class="actor-name">${e.phase===2?'Ⅱ':''}</div><div class="status-row">${statuses(e)}</div>${selectedCard&&CARDS[selectedCard.id].kind==='攻击'?`<div class="damage-preview" title="${engine!.preview(selectedCard,e)}">${engine!.preview(selectedCard,e).replace(' damage · ',' → −').replace(' HP lost','')}</div>`:''}</div></button>`;}
function battle(r:Run){const b=r.battle!,p=positions(innerWidth,innerHeight,r),c=b.hand.find(c=>c.uid===selected);const reason=c?engine!.canPlay(c):undefined;
 return `<main class="battle-screen ${busy?'busy':''}"><div class="turn-label" title="${busy?'Resolving action':`Your turn ${b.turn}`}"><i></i>${busy?'…':String(b.turn).padStart(2,'0')}</div><button class="hero-target" data-action="self" aria-label="Use selected card on yourself" style="left:${p.hero.x}px;top:${p.hero.y-p.hero.height}px;width:${Math.max(70,p.hero.height*.75)}px;height:${p.hero.height+10}px"></button><div class="hero-bar" style="left:${p.hero.x}px;top:${p.hero.y+7}px"><div class="status-row">${statuses(b.player)}</div></div>${p.enemies.map(v=>enemyPanel(b.enemies.find(e=>e.uid===v.uid)!,v.x,Math.max(v.y,v.height+102),v.height,r)).join('')}
 ${c?`<div class="battle-hint">${reason??(CARDS[c.id].target?'Choose a target':'Confirm play')}</div>`:''}
 <section class="hand-area"><button class="pile draw-pile" data-action="draw" aria-label="View draw pile" title="Draw pile">${icon('deck')}<b>${b.draw.length}</b></button><div class="hand-scroll"><div class="hand">${b.hand.map(v=>card(v,`select:${v.uid}`,`${selected===v.uid?'selected':''} ${engine!.canPlay(v)?'unplayable':''}`)).join('')}${!b.hand.length?'<p class="empty-hand">—</p>':''}</div></div><button class="pile discard-pile" data-action="discard" aria-label="View discard pile" title="Discard pile">${icon('deck')}<b>${b.discard.length}</b></button></section>
 <footer class="combat-controls"><div class="energy" title="Energy ${b.energy} / 3">${icon('energy')}<b>${b.energy}</b><small>/ 3</small></div><button class="heat-control" data-action="heat-info" title="Heat ${b.heat} / 6; high heat at 4+; overheat at 6 when ending your turn"><div class="heat-title">${icon('heat')}<b>${b.heat}</b></div><div class="heat-gauge ${b.heat===6?'overheat':''}">${Array.from({length:6},(_,i)=>`<i class="${i<b.heat?'lit':''}"></i>`).join('')}</div>${b.heat===6?`<small class="heat-warning">${icon('heart')}−${engine!.has(7)&&!b.glove?1:4}</small>`:''}</button>${button(`${icon('vent')}Vent`,'vent','vent-button',b.vented||b.heat<2||!!r.pending,`title="${b.vented?'Already used this turn':`Spend 2 Heat, gain ${engine!.ventValue()} Block`}"`)}${c&&!CARDS[c.id].target?button('Play','play','play-button',!!reason):''}${button(`End${icon('end')}`,'end','primary end-button',!!r.pending,'aria-label="End turn" title="End turn · E"')}</footer>${b.powers.length?`<button class="power-badges" data-action="powers" aria-label="View active powers">${b.powers.map(c=>`<img src="${art(`card-${CARDS[c.id].art}`)}" title="${esc(cardName(c)+': '+cardText(c))}" alt="${cardName(c)}"/>`).join('')}</button>`:''}</main>`;
}
function reward(r:Run){return `<main class="choice-screen reward-screen">${pageTitle('SPOILS OF THE FORGE','Choose a card',r.rewardGold?`Victory · ${r.rewardGold} gold${r.rewardRelic!==undefined?` · ${RELICS[r.rewardRelic].name}`:''}`:'Take one card, or keep your deck lean.')}<div class="choice-cards">${r.reward.map((id,i)=>card({id,uid:i,upgraded:false},`reward:${id}`,rewardSelected===id?'selected':'',true)).join('')}</div><div class="screen-actions">${button('View Deck','deck','quiet')}${button('Take Card','reward-confirm','primary',!rewardSelected)}${button('Skip','reward-skip','quiet')}</div></main>`;}
function rest(r:Run){return `<main class="choice-screen rest-screen">${pageTitle('A MOMENT OF WARMTH','At the hearth','Rest your wounds or sharpen your deck.')}<div class="service-options"><button class="service" data-action="rest:heal"><span class="service-icon">${icon('rest')}</span><h2>Rest</h2><p>Heal <b>21</b> HP</p><small>${r.hp} → ${Math.min(r.maxHp,r.hp+21)} / ${r.maxHp}</small></button><button class="service" data-action="rest:upgrade" ${!r.deck.some(c=>!c.upgraded&&CARDS[c.id].kind!=='状态')?'disabled':''}><span class="service-icon">${icon('hammer')}</span><h2>Upgrade</h2><p>Upgrade one card for this run</p><small>Choose one service</small></button></div></main>`;}
function shop(r:Run){const s=r.shop!;return `<main class="choice-screen shop-screen">${pageTitle('THE COPPER EXCHANGE','Copper Exchange','One of each item. Spend wisely.')}<div class="shop-content"><div class="shop-cards">${s.cards.map((id,i)=>`<div class="shop-item">${id?card({id,uid:i,upgraded:false}):'<div class="sold">Sold out</div>'}${id?button(`Buy · ${engine!.price(id)} ◉`,`buy:${i}`,'small-button',r.gold<engine!.price(id)):''}</div>`).join('')}</div><div class="shop-services">${s.relic!=null?`<div class="shop-relic">${relic(s.relic,true)}${button('Buy Relic · 150 ◉','buy-relic','small-button',r.gold<150)}</div>`:'<div class="sold">Relic sold out</div>'}<div class="delete-service"><h3>Refine your deck</h3><p>Permanently remove one card</p>${button(s.removed?'Used':`Remove · ${r.deleteCost} ◉`,'remove','small-button',s.removed||r.gold<r.deleteCost||r.deck.length<=1)}</div></div></div>${button('Leave Shop →','leave','primary')}</main>`;}
const EVENTS=[
 {over:'LETTERS IN ASH',name:'Burning Mailbox',text:'A mailbox smolders at the end of the bridge. Inside, a forgotten sigil is still too hot to touch.',icon:'✉',choices:['Take the sigil · Pay 8 HP, choose an uncommon card']},
 {over:'AN OLD BARGAIN',name:'Furnace Bargain',text:'The furnace keeper asks for your coins, or a rusted memory. Nothing here comes without a price.',icon:'⚖',choices:['Pay 45 gold · Remove a card','Accept the gift · Gain 35 gold and add Rust']},
 {over:'LIGHT IN THE WIND',name:'Windward Beacon',text:'A faint light leads you to an abandoned beacon. Its warm hearth offers shelter; old sigils wait in a cabinet.',icon:'◈',choices:['Rest by the fire · Heal 10 HP','Browse the sigils · Pay 30 gold, choose a common card']},
 {over:'THE SILENT SMITH',name:'Silent Smith',text:'The smith taps your hammer without a word. A stronger sigil awaits, but your furnace will need time to settle.',icon:'⚒',choices:['Accept the upgrade · Next battle starts with 2 Energy']}
];
function event(r:Run){const e=EVENTS[r.event];return `<main class="event-screen"><div class="event-sigil">${e.icon}</div><div class="event-copy">${pageTitle(e.over,e.name,e.text)}<div class="event-options">${e.choices.map((label,i)=>button(`<span>${label}</span><b>›</b>`,`event:${i}`,'event-option',r.event===0?r.hp<=8:r.event===1&&i===0?r.gold<45:r.event===2&&i===1?r.gold<30:r.event===3?!r.deck.some(c=>!c.upgraded&&CARDS[c.id].kind!=='状态'):false)).join('')}${button('Leave','event:2','quiet')}</div></div></main>`;}
function chest(r:Run){return `<main class="choice-screen chest-screen">${pageTitle('A RELIC OF THE OLD CITY','A gift from the old city','A surviving relic waits beneath the rusted lock.')}${r.rewardRelic!==undefined?relic(r.rewardRelic,true):'<p>You have collected every relic.</p>'}${button('Take Relic','chest','primary')}</main>`;}
function finish(r:Run){return `<main class="choice-screen finish-screen"><div class="finish-sigil">${r.won?'◈':'◇'}</div>${pageTitle(r.won?'THE HARBOR BURNS AGAIN':'THE EMBER WILL RETURN',r.won?'Ash Harbor rekindled':'The flame rests',r.won?'The Iron Bell falls silent. Chapter I is complete.':'Every journey leaves a lesson. Light the furnace again.')}<div class="run-stats"><div><b>${r.map.find(n=>n.id===r.current)?.floor??0}<small>/12</small></b><span>Floor reached</span></div><div><b>${r.stats.battles}</b><span>Battles won</span></div><div><b>${r.stats.heat}</b><span>Peak Heat</span></div><div><b>${r.stats.overheat}</b><span>Overheats</span></div></div><div class="finish-relics">${r.relics.map(i=>relic(i)).join('')}</div><div class="screen-actions">${button('New Journey','new','primary')}${button('View Deck','deck','quiet')}${button('Same Seed','same-seed','quiet')}${button('Main Menu','title','quiet')}</div><p class="subtle">Seed ${r.seed} · ${r.deck.length} ${r.deck.length===1?'card':'cards'} · ${r.stats.turns} ${r.stats.turns===1?'turn':'turns'}</p></main>`;}
function pendingView(r:Run){const p=r.pending!;const cards=p.type==='recover'?r.battle!.discard.filter(c=>c.id!=='C15'):p.type==='retain'?r.battle!.hand.filter(c=>!CARDS[c.id].retain&&!c.keep):r.deck.filter(c=>p.type==='remove'||!c.upgraded&&CARDS[c.id].kind!=='状态');const labels={recover:'Reforge · Return a card',retain:'Memory Sigil · Retain a card',upgrade:'Upgrade a card',remove:'Remove a card'};return `<div class="modal-backdrop mandatory"><section class="modal selection-modal" role="dialog" aria-modal="true" aria-label="${labels[p.type]}"><div class="modal-header"><h2>${labels[p.type]}</h2></div><p class="subtle">${p.type==='upgrade'?'Choose a card. Its upgraded effect is shown below.':p.type==='remove'?'Choose a card to remove from this run.':p.type==='retain'?'Keep a card, then let the enemies act.':'Return a card and continue your turn.'}</p><div class="card-grid">${cards.map(c=>`<div>${card(c,`pending:${c.uid}`)}${p.type==='upgrade'?`<div class="upgrade-preview">Upgraded: ${esc(cardText({...c,upgraded:true}))}${cost({...c,upgraded:true})!==cost(c)?` Cost ${cost({...c,upgraded:true})}`:''}</div>`:''}</div>`).join('')}</div>${p.type==='retain'?button('Skip Retain','pending-skip','quiet'):''}</section></div>`;}
function modalView(){if(!modal)return '';const r=engine?.run;let content='',title='';
 if(modal==='settings'){title='Settings';content=`<div class="settings-row"><div><h3>Sound effects</h3><p>Card, forge and vent feedback</p></div>${button(muted?'Muted':'On','toggle-sound','small-button')}</div><div class="settings-row"><div><h3>Reduced motion</h3><p>Less movement, no screen shake</p></div>${button(reduced?'On':'Off','toggle-motion','small-button')}</div><p class="subtle">Progress saves after each complete action.</p><div class="screen-actions">${button('Guide','rules','quiet')}${r?.screen==='battle'?button('Battle Log','log','quiet'):''}</div>`;}
 else if(modal==='heat-info'){title='Heat';content=`<div class="rules-content"><p><b>4–5 · High heat.</b> Empowers marked cards.</p><p><b>6 · Overheat.</b> End your turn to lose ${r?.battle&&engine!.has(7)&&!engine!.b.glove?1:4} HP directly, then set Heat to 2.</p><p>Cool by 1 at turn start. Once per turn, Vent spends 2 Heat for ${r?.battle?engine!.ventValue():4} Block.</p></div>`;}
 else if(modal==='relics'){title='Relics';content=`<div class="relic-grid">${r?.relics.map(i=>relic(i,true)).join('')}</div>`;}
 else if(modal==='powers'){title='Active powers';content=`<div class="card-grid">${r?.battle?.powers.map(c=>card(c)).join('')}</div>`;}
 else if(modal==='rules'){title='Smith\'s Guide';content=`<div class="rules-content"><h3>Read the intent. Plan the turn.</h3><p>Start each turn with 3 Energy and draw 5 cards. Hand limit: 10. Enemies act when you end your turn. Your Block clears at your next turn start.</p><div class="rule-columns"><div><b>Heat → High heat</b><p>At Heat 4+, marked cards become stronger. Naturally cool by 1 at turn start.</p></div><div><b>Vent → Block</b><p>Once per turn, spend 2 Heat for 4 Block without using Energy. Old Furnace Core adds 2 on your first Vent each battle.</p></div><div><b>Heat 6 → Overheat</b><p>End at Heat 6 to lose 4 HP through Block, then set Heat to 2. Killing the last enemy ends the battle immediately.</p></div></div><h3>Keywords</h3><p>${KEYWORDS}</p><h3>Controls</h3><p>Click a card, then its target. Skills and powers can target yourself or use Play. Drag upward to play; swipe sideways to browse your hand. Keyboard: 1–0 select, ←/→ choose a target, Enter confirm, Esc cancel, E end turn. Space picks up a card; arrows move it and Enter releases it.</p><h3>Your journey</h3><p>Card rewards can be skipped. At a rest stop, choose healing or an upgrade. Shops offer cards, relics and card removal. Defeat the Iron Bell Overseer on floor 12 to complete Chapter I.</p></div>`;}
 else if(modal==='new-confirm'){title='Start a new journey?';content=`<p>This will replace your current run.</p><div class="screen-actions">${button('New Journey','new','primary')}${button('Keep Current Run','close','quiet')}</div>`;}
 else if(modal==='home'){title='Run menu';content=`<p class="subtle">Your progress is saved.</p><div class="menu-actions">${button('Resume','close','primary')}${button('Guide','rules','quiet')}${button('Main Menu','title','quiet')}${button('New Journey','new-confirm','quiet')}</div>`;}
 else if(r){
  if(modal==='log'){title='Battle log';content=`<div class="battle-log">${r.battle?.log.slice().reverse().map(s=>`<p>${esc(s)}</p>`).join('')}</div>`;}
  else {const cards=modal==='draw'?r.battle?.draw:modal==='discard'?r.battle?.discard:modal==='exhaust'?r.battle?.exhaust:r.deck;title=modal==='draw'?'Draw pile · Unordered':modal==='discard'?'Discard pile':modal==='exhaust'?'Exhaust pile':`Deck · ${r.deck.length} ${r.deck.length===1?'card':'cards'}`;
   const sorted=[...(cards??[])].sort((a,b)=>a.id.localeCompare(b.id)||Number(b.upgraded)-Number(a.upgraded));content=`${modal==='discard'?button(`Exhaust pile · ${r.battle?.exhaust.length??0}`,'exhaust','quiet'):''}<div class="card-grid">${sorted.map(c=>card(c)).join('')||'<p class="subtle">No cards here.</p>'}</div>`;}
 }
 return `<div class="modal-backdrop"><section class="modal ${modal==='rules'?'rules-modal':''}" role="dialog" aria-modal="true" aria-label="${title}"><div class="modal-header"><h2>${title}</h2><button class="icon-button" data-action="close" aria-label="Close">×</button></div>${content}</section></div>`;
}
function stats(){const r=engine?.run;return r?{hp:r.hp,gold:r.gold,deck:r.deck.length,energy:r.battle?.energy??0,heat:r.battle?.heat??0,block:r.battle?.player.block??0,phase:Math.max(1,...(r.battle?.enemies.map(e=>e.phase)??[]))}:undefined;}
function refreshInput(){const blocked=busy||!!modal||!!engine?.run.pending;app.querySelectorAll<HTMLButtonElement>('.battle-screen button').forEach(b=>{b.disabled=b.dataset.ruleDisabled==='true'||blocked;});app.querySelector('.battle-screen')?.classList.toggle('busy',busy);const label=app.querySelector('.turn-label');if(label&&engine?.run.screen==='battle')label.innerHTML=`<i></i>${busy?'…':String(engine.b.turn).padStart(2,'0')}`;}
function render(syncWorld=true){
 const before=motion.capture(),r=engine?.run;const previousScreen=document.body.dataset.screen;const previousMapNode=app.querySelector<HTMLElement>('.route-node.current')?.dataset.action,mapTop=app.querySelector<HTMLElement>('.map-scroll')?.scrollTop;const scrolls=new Map<string,number>();
 if(previousScreen===(r?.screen??'menu'))for(const cls of ['hand-scroll','choice-cards','shop-cards']){const el=app.querySelector<HTMLElement>(`.${cls}`);if(el)scrolls.set(cls,el.scrollLeft);}
 document.body.dataset.screen=r?.screen??'menu';document.body.classList.toggle('reduced',reduced);motion.reduced=reduced;motion.muted=muted;world.reduced(reduced);if(syncWorld)world.sync(r);
 const views={forge,map,battle,reward,rest,shop,event,chest,finish};app.innerHTML=(r?header(r)+views[r.screen](r):menu())+(r?.pending?pendingView(r):'')+modalView();
 for(const [cls,left]of scrolls){const el=app.querySelector<HTMLElement>(`.${cls}`);if(el)el.scrollLeft=left;}
 app.querySelector<HTMLElement>('.hand .card.selected')?.scrollIntoView({block:'nearest',inline:'nearest'});
 app.querySelectorAll<HTMLButtonElement>('.battle-screen button').forEach(b=>{b.dataset.ruleDisabled=String(b.disabled);});refreshInput();
 if(r?.screen==='map'){const cur=app.querySelector<HTMLElement>('.route-node.current'),scroll=app.querySelector<HTMLElement>('.map-scroll');if(cur&&scroll)scroll.scrollTop=previousScreen==='map'&&previousMapNode===`node:${r.current}`&&mapTop!==undefined?mapTop:cur.offsetTop-scroll.clientHeight*.5;}
 if(previousScreen!==(r?.screen??'menu'))motion.view(r?.screen??'menu');displayed=stats();return motion.hand(before,r?.battle?.turn??0,r?.screen??'menu');
}
function positiveFeedback(before:ReturnType<typeof stats>,after:ReturnType<typeof stats>){if(!before||!after)return;const bump=(selector:string,value:number,color?:string)=>{const el=app.querySelector<HTMLElement>(selector);if(el){const p=center(el.getBoundingClientRect());motion.pop(`+${value}`,{x:p.x,y:selector.includes('stat')?70:p.y-20},color);motion.pulse(selector,color);}};
 if(after.gold>before.gold){bump('.gold-stat',after.gold-before.gold,'#e7bc80');tone('reward');}if(after.hp>before.hp){bump('.hp-stat',after.hp-before.hp);tone('block');}if(after.hp<before.hp)motion.pulse('.hp-stat','#d66a50');if(after.deck>before.deck){bump('.hud-right [data-action="deck"]',after.deck-before.deck);tone('reward');}
 if(after.energy!==before.energy)motion.pulse('.energy');if(after.heat!==before.heat){motion.pulse('.heat-control',after.heat>before.heat?'#e7bc80':'#78d6b6');if(after.heat>=4&&before.heat<4){motion.pop('High heat',{x:innerWidth*.25,y:innerHeight-125},'#e7bc80');tone('heat');world.heat();}}
 if(after.block>before.block&&engine?.run.screen==='battle'){world.guard(after.block-before.block);tone('block');}if(after.phase>before.phase){motion.banner('Overseer enraged','danger');tone('heat');return 850;}return 0;
}
async function changed(){if(!engine)return;const active=engine,epoch=actionEpoch,before=displayed,after=stats(),effects=engine.effects.splice(0),transition=document.body.dataset.screen==='battle'&&engine.run.screen!=='battle';save();busy=true;
 let duration=transition?0:render(document.body.dataset.screen!=='battle');duration=Math.max(duration,world.effects(effects,engine.run.battle?.enemies.filter(e=>e.hp<=0).map(e=>e.uid)??[]),positiveFeedback(before,after)??0);
 if(transition){duration=Math.max(duration,reduced?180:850);if(engine.run.screen==='reward'||engine.run.won){motion.banner(engine.run.won?'Harbor rekindled':'Victory');tone('win');}else motion.banner('Flame extinguished','danger');}
 if(duration)await motion.wait(duration);if(engine!==active||epoch!==actionEpoch)return;busy=false;if(transition)render();else{world.sync(engine.run);refreshInput();}
}
function start(seed?:number){actionEpoch++;input.cancel();motion.clear();displayed=undefined;engine=new Engine(seed??(Date.now()>>>0));selected=undefined;target=undefined;rewardSelected=undefined;modal=undefined;busy=false;tone('heat');void changed();}
async function performEnd(){if(!engine||busy||modal||engine.run.pending||input.dragging)return;selected=undefined;target=undefined;
 if(engine.b.powers.some(c=>c.id==='C22')&&engine.b.hand.some(c=>!CARDS[c.id].retain)){engine.endTurn();void changed();return;}
 const active=engine,epoch=actionEpoch;busy=true;refreshInput();world.enemyMotion(engine.living().filter(e=>engine!.action(e).damage).map(e=>e.uid));tone('end');await motion.wait(reduced?30:200);if(engine!==active||epoch!==actionEpoch)return;engine.endTurn();await changed();
}
async function playCard(cardUid:number,targetUid?:number,ghost?:HTMLElement){if(!engine||busy||modal||engine.run.pending||engine.run.screen!=='battle'){ghost?.remove();return;}const c=engine.b.hand.find(c=>c.uid===cardUid),el=app.querySelector<HTMLElement>(`.hand .card[data-uid="${cardUid}"]`);if(!c||!el){ghost?.remove();return;}const reason=engine.canPlay(c);if(reason||CARDS[c.id].target&&targetUid===undefined){ghost?.remove();notify(reason??'Choose an enemy.');tone('reject');return;}
 const active=engine,epoch=actionEpoch,p=positions(innerWidth,innerHeight,engine.run),enemy=p.enemies.find(e=>e.uid===targetUid),destination=enemy?{x:enemy.x,y:enemy.y-enemy.height*.55}:CARDS[c.id].kind==='攻击'?{x:p.enemies.reduce((sum,e)=>sum+e.x,0)/Math.max(1,p.enemies.length),y:p.hero.y-p.hero.height*.5}:{x:p.hero.x,y:p.hero.y-p.hero.height*.5};
 busy=true;refreshInput();if(CARDS[c.id].kind==='攻击')world.playerMotion();await motion.fly(el,destination,ghost);if(engine!==active||epoch!==actionEpoch)return;
 if(engine.play(cardUid,targetUid)){motion.consumed.add(cardUid);selected=undefined;target=undefined;if(CARDS[c.id].kind!=='攻击')motion.burst(destination,'#78d6b6');await changed();}else{busy=false;render();}
}
function playSelected(uid?:number){if(selected!==undefined)void playCard(selected,uid);}
async function collectReward(){if(!engine||!rewardSelected||busy)return;const active=engine,epoch=actionEpoch,id=rewardSelected,el=app.querySelector<HTMLElement>('.choice-cards .card.selected'),deck=app.querySelector<HTMLElement>('.hud-right [data-action="deck"]');busy=true;refreshInput();if(el&&deck)await motion.fly(el,center(deck.getBoundingClientRect()));if(engine!==active||epoch!==actionEpoch)return;engine.chooseReward(id);rewardSelected=undefined;await changed();}
function dispatch(action:string){
 const [name,arg]=action.split(':');const r=engine?.run;
 if(busy)return;
 if(r?.pending&&!['pending','pending-skip'].includes(name))return;
 switch(name){
  case 'new':start();return;case 'same-seed':start(r?.seed);return;
  case 'continue':{const saved=loadSave();if(saved){engine=new Engine(saved.seed,saved);selected=undefined;modal=undefined;render();}return;}
  case 'title':save();engine=undefined;selected=undefined;modal=undefined;render();return;
  case 'close':modal=undefined;render();return;
  case 'toggle-sound':muted=!muted;break;case 'toggle-motion':reduced=!reduced;break;
  case 'home':case 'settings':case 'rules':case 'relics':case 'heat-info':case 'powers':case 'deck':case 'draw':case 'discard':case 'exhaust':case 'log':case 'new-confirm':modal=name;render();return;
 }
 if(name==='toggle-sound'||name==='toggle-motion'){try{localStorage.setItem(SETTINGS,JSON.stringify({muted,reduced}));}catch{}render();return;}
 if(!engine||!r)return;
 switch(name){
  case 'forge':engine.forge(arg);break;
  case 'node':if(!engine.enter(arg)){const n=r.map.find(n=>n.id===arg);notify(n?`${NODE_INFO[n.kind].name} — ${NODE_INFO[n.kind].hint} Choose a glowing node.`:'Choose a connected node.');return;}break;
  case 'select':{const c=engine.b.hand.find(c=>c.uid===Number(arg));if(!c)return;const reason=engine.canPlay(c);if(reason){notify(reason);tone('reject');motion.pulse(`.hand .card[data-uid="${c.uid}"]`,'#d66a50');return;}selected=selected===c.uid?undefined:c.uid;target=engine.living()[0]?.uid;tone('select');render();return;}
  case 'target':target=Number(arg);if(selected!==undefined){playSelected(target);}else{const e=engine.b.enemies.find(e=>e.uid===target);if(e)notify(`${ENEMIES[e.id].name} — next: ${engine.intention(e)}`);}return;
  case 'self':{const c=engine.b.hand.find(c=>c.uid===selected);if(c&&!CARDS[c.id].target)playSelected();return;}
  case 'play':playSelected();return;
  case 'vent':if(!engine.vent())return;tone('vent');break;
  case 'end':performEnd();return;
  case 'reward':rewardSelected=arg;tone();render();return;
  case 'reward-confirm':void collectReward();return;
  case 'reward-skip':engine.chooseReward();rewardSelected=undefined;break;
  case 'rest':engine.rest(arg as 'heal'|'upgrade');break;
  case 'buy':if(!engine.buy(Number(arg)))notify('Not enough gold, or this item is sold out.');else tone();break;
  case 'buy-relic':engine.buyRelic();break;case 'remove':engine.removeCard();break;case 'leave':engine.leave();break;
  case 'event':engine.eventChoice(Number(arg));break;case 'chest':engine.chest();break;
  case 'pending':{const type=r.pending?.type;if(type==='retain')motion.kept.add(Number(arg));if(engine.choosePending(Number(arg))&&type==='upgrade'){motion.pop('Upgraded',{x:innerWidth*.5,y:innerHeight*.45},'#e7bc80');tone('reward');}break;}case 'pending-skip':engine.choosePending();break;
 }
 changed();
}
app.addEventListener('click',ev=>{const node=(ev.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(node&&!node.disabled)dispatch(node.dataset.action!);});
const input=cardInput({root:app,blocked:()=>busy||!!modal||!!engine?.run.pending||engine?.run.screen!=='battle',selected:()=>selected,card:uid=>{const c=engine?.run.battle?.hand.find(c=>c.uid===uid);return c?{target:!!CARDS[c.id].target,kind:CARDS[c.id].kind,reason:engine!.canPlay(c)}:undefined;},select:uid=>{selected=uid;target=undefined;tone('select');app.querySelectorAll<HTMLElement>('.hand .card').forEach(el=>el.classList.toggle('selected',Number(el.dataset.uid)===uid));const c=engine!.b.hand.find(c=>c.uid===uid)!;app.querySelectorAll<HTMLElement>('.enemy-target').forEach(el=>{el.classList.toggle('targeting',!!CARDS[c.id].target);el.querySelector('.damage-preview')?.remove();if(CARDS[c.id].kind==='攻击'){const e=engine!.b.enemies.find(e=>e.uid===Number(el.dataset.action!.split(':')[1]))!;const preview=document.createElement('div');preview.className='damage-preview';preview.textContent=engine!.preview(c,e).replace(' damage · ',' → −').replace(' HP lost','');el.querySelector('.actor-bar')?.append(preview);}});},play:(uid,targetUid,ghost)=>{void playCard(uid,targetUid,ghost);},cancel:()=>{selected=undefined;target=undefined;render();},reject:message=>{notify(message);tone('reject');}});
window.addEventListener('keydown',ev=>{
 if(ev.repeat&&(ev.key==='Enter'||ev.key.toLowerCase()==='e'))return;
 if(ev.defaultPrevented||input.dragging||['INPUT','TEXTAREA'].includes((ev.target as HTMLElement)?.tagName))return;
 if(ev.key==='Escape'){if(busy||engine?.run.pending)return;modal=undefined;selected=undefined;target=undefined;render();return;}
 if(modal||busy||!engine||engine.run.pending||engine.run.screen!=='battle')return;
 if(/^[0-9]$/.test(ev.key)){const i=ev.key==='0'?9:Number(ev.key)-1;const c=engine.b.hand[i];if(c)dispatch(`select:${c.uid}`);}
 if(ev.key==='ArrowLeft'||ev.key==='ArrowRight'){ev.preventDefault();const ids=engine.living().map(e=>e.uid);const index=Math.max(0,ids.indexOf(target??-1));target=ids[(index+(ev.key==='ArrowRight'?1:-1)+ids.length)%ids.length];render();}
 if(ev.key==='Enter'&&selected!==undefined){ev.preventDefault();const c=engine.b.hand.find(c=>c.uid===selected)!;playSelected(CARDS[c.id].target?target:undefined);}
 if(ev.key.toLowerCase()==='e'&&selected===undefined){ev.preventDefault();performEnd();}
});
window.addEventListener('resize',()=>render());window.addEventListener('world-ready',()=>world.sync(engine?.run));
world.start();
// Fixed mid-run fixtures are available only in development playtest URLs, with isolated saves.
if(scenario==='boss'){
 engine=new Engine(42);const r=engine.run;r.current='12-1';r.path=['0-1','1-1','2-1','3-1','4-0','5-0','6-1','7-0','8-0','9-0','10-0','11-1','12-1'];
 r.deck=['C12','C07','C04','C11','C24','C03','C13','C19','C20','C17'].map(id=>({...engine!.makeCard(id),upgraded:true}));r.relics=[0,1,4,7];engine.startBattle(['boss']);
 const initial=['C12','C07','C04','C11','C24'];engine.b.hand=initial.map(id=>({...r.deck.find(c=>c.id===id)!}));engine.b.draw=r.deck.filter(c=>!initial.includes(c.id)).map(c=>({...c}));engine.b.discard=[];engine.b.enemies[0].hp=78;engine.b.heat=4;
}else if(scenario==='cards'){
 engine=new Engine(42);engine.forge('C01');engine.enter('1-1');engine.run.deck=Object.keys(CARDS).flatMap(id=>[false,true].map(upgraded=>({...engine!.makeCard(id),upgraded})));engine.b.hand=['C12','C15','C17','C21','C22'].map(id=>({...engine!.makeCard(id),upgraded:true}));engine.b.energy=10;
}else if(scenario==='fatal'){
 engine=new Engine(42);engine.forge('C01');engine.enter('1-1');engine.run.hp=3;engine.b.heat=6;
}else if(scenario==='services'){
 engine=new Engine(42);engine.forge('C01');engine.run.current='2-1';engine.enter('3-1');engine.run.gold=240;
}else if(scenario==='rest'||scenario==='chest'){
 engine=new Engine(42);engine.forge('C01');engine.run.hp=35;engine.run.current=scenario==='rest'?'10-0':'5-0';engine.enter(scenario==='rest'?'11-1':'6-1');
}
render();
// Read-only UI audit complements screenshots; normal input owns all actions.
function uiAudit(){return {english:!/[\u3400-\u9fff]/.test(app.textContent??''),cardOverflow:Array.from(app.querySelectorAll<HTMLElement>('.card-name,.card-text')).filter(el=>{const b=el.getBoundingClientRect();if(el.classList.contains('card-name'))return el.scrollHeight>el.clientHeight+2||el.scrollWidth>el.clientWidth+2;return Array.from(el.children).some(child=>{const r=child.getBoundingClientRect();return r.top<b.top-2||r.bottom>b.bottom+2;});}).map(el=>({uid:el.closest<HTMLElement>('.card')?.dataset.uid,area:el.className,text:el.textContent})),notices:document.querySelectorAll('.toast').length};}
// Read-only state for identifying deterministic gameplay boundaries; normal input owns all actions.
if(import.meta.env.DEV){(globalThis as unknown as {__OHMYGAME_PLAYTEST__:unknown}).__OHMYGAME_PLAYTEST__={snapshot:()=>({viewport:{width:innerWidth,height:innerHeight,contentWidth:document.documentElement.scrollWidth},ui:uiAudit(),fontLoaded:document.fonts.check('16px Georgia'),muted,reduced,feedback:document.querySelectorAll('.feedback-number,.battle-banner,.card-ghost,.motion-spark').length,screen:engine?.run.screen??'menu',modal,busy,selected,drag:input.snapshot,animations:document.getAnimations().filter(a=>a.playState==='running').length,seed:engine?.run.seed,hp:engine?.run.hp,gold:engine?.run.gold,deckCount:engine?.run.deck.length,relics:engine?.run.relics,current:engine?.run.current,available:engine?.available().map(id=>engine?.run.map.find(n=>n.id===id)),pending:engine?.run.pending,reward:engine?.run.reward,shop:engine?.run.shop,event:engine?.run.event,won:engine?.run.won,stats:engine?.run.stats,battle:engine?.run.screen==='battle'?{turn:engine.b.turn,energy:engine.b.energy,heat:engine.b.heat,block:engine.b.player.block,vented:engine.b.vented,hand:engine.b.hand.map(c=>({...c,name:cardName(c),cost:cost(c)})),enemies:engine.b.enemies.map(e=>({...e,name:ENEMIES[e.id].name,intent:engine!.intention(e)})),piles:{draw:engine.b.draw.length,discard:engine.b.discard.length,exhaust:engine.b.exhaust.length},log:engine.b.log.slice(-4)}:undefined}),setSeed:(seed:number)=>{start(seed);},reset:()=>{actionEpoch++;input.cancel();motion.clear();engine=undefined;selected=undefined;modal=undefined;busy=false;displayed=undefined;render();}};}
